// Regenerates the knowledge-base master index and a health report from the
// compiled topics. Deterministic, no LLM/key needed. Run after the
// knowledge-compiler agent has created or updated topics:  npm run knowledge

import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const TOPICS_DIR = join(root, "src", "content", "topics");
const RAW_DIR = join(root, "raw");
const OUTPUTS_DIR = join(root, "outputs");
const INDEX_FILE = join(TOPICS_DIR, "_index.md");

// Seed topics defined in code (src/lib/topics.ts), not as .md files.
const SEED_SLUGS = [
  "stoicism", "ethics", "epistemology", "existentialism",
  "logic", "metaphysics", "political-philosophy", "philosophy-of-mind",
];

const CATEGORY_ORDER = [
  "Ancient Philosophy", "Medieval Philosophy", "Modern Philosophy",
  "Core Philosophy", "Applied Philosophy", "Logic",
];

function toSlug(name) {
  return name
    .toLowerCase()
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

// Minimal frontmatter parser matching src/lib/content.ts behavior.
function parseFrontmatter(raw) {
  const m = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
  if (!m) return { data: {}, body: raw };
  const data = {};
  let key = null;
  for (const line of m[1].split("\n")) {
    const t = line.trim();
    if (!t) continue;
    if (t.startsWith("- ")) {
      if (key) (data[key] ??= []).push(t.slice(2).replace(/^["']|["']$/g, ""));
    } else {
      const i = t.indexOf(":");
      if (i === -1) continue;
      key = t.slice(0, i).trim();
      let v = t.slice(i + 1).trim();
      if (v.startsWith("[") && v.endsWith("]")) {
        data[key] = v.slice(1, -1).split(",").map((s) => s.trim().replace(/^["']|["']$/g, "")).filter(Boolean);
        key = null;
      } else if (v === "") {
        data[key] = [];
      } else {
        data[key] = v.replace(/^["']|["']$/g, "");
        key = null;
      }
    }
  }
  return { data, body: m[2].trim() };
}

async function loadTopics() {
  const files = (await readdir(TOPICS_DIR)).filter(
    (f) => f.endsWith(".md") && !f.startsWith("_")
  );
  const topics = [];
  for (const file of files) {
    const raw = await readFile(join(TOPICS_DIR, file), "utf8");
    const { data, body } = parseFrontmatter(raw);
    const slug = data.id ? String(data.id) : toSlug(file.replace(/\.md$/, ""));
    topics.push({
      file,
      slug,
      name: data.name || file.replace(/\.md$/, ""),
      tagline: data.tagline || "",
      category: data.category || "",
      tags: Array.isArray(data.tags) ? data.tags : [],
      relatedTopics: Array.isArray(data.relatedTopics) ? data.relatedTopics : [],
      lang: data.lang || "es",
      bodyLength: body.length,
    });
  }
  return topics;
}

function buildIndex(topics) {
  const known = new Set([...topics.map((t) => t.slug), ...SEED_SLUGS]);
  const byCategory = new Map();
  for (const t of topics) {
    const cat = t.category || "Uncategorized";
    (byCategory.get(cat) ?? byCategory.set(cat, []).get(cat)).push(t);
  }
  const cats = [...byCategory.keys()].sort(
    (a, b) =>
      (CATEGORY_ORDER.indexOf(a) + 1 || 99) - (CATEGORY_ORDER.indexOf(b) + 1 || 99) ||
      a.localeCompare(b)
  );

  let out = `# Knowledge Base Index\n\n`;
  out += `> Auto-generated by \`npm run knowledge\`. Do not edit by hand.\n\n`;
  out += `${topics.length} topics across ${cats.length} categories · generated ${new Date().toISOString().slice(0, 10)}\n`;
  for (const cat of cats) {
    const list = byCategory.get(cat).sort((a, b) => a.name.localeCompare(b.name));
    out += `\n## ${cat} (${list.length})\n\n`;
    for (const t of list) {
      const links = t.relatedTopics.filter((s) => known.has(s)).length;
      out += `- **${t.name}** (\`${t.slug}\`) — ${t.tagline || "—"}`;
      out += `  ·  ${t.tags.length} tags, ${links} links, lang \`${t.lang}\`\n`;
    }
  }
  return out;
}

function healthCheck(topics) {
  const known = new Set([...topics.map((t) => t.slug), ...SEED_SLUGS]);
  const referenced = new Set();
  for (const t of topics) for (const r of t.relatedTopics) referenced.add(r);

  const issues = { broken: [], orphans: [], missing: [], duplicates: [] };
  const seen = new Map();

  for (const t of topics) {
    if (seen.has(t.slug)) issues.duplicates.push(`${t.slug} (${t.file} & ${seen.get(t.slug)})`);
    else seen.set(t.slug, t.file);

    for (const r of t.relatedTopics) {
      if (!known.has(r)) issues.broken.push(`${t.slug} → ${r}`);
    }
    const missingFields = [];
    if (!t.tagline) missingFields.push("tagline");
    if (!t.category) missingFields.push("category");
    if (t.tags.length === 0) missingFields.push("tags");
    if (missingFields.length) issues.missing.push(`${t.slug}: ${missingFields.join(", ")}`);

    if (t.relatedTopics.length === 0 && !referenced.has(t.slug)) {
      issues.orphans.push(t.slug);
    }
  }
  return issues;
}

async function uncompiledRaw(topics) {
  try {
    const files = (await readdir(RAW_DIR)).filter(
      (f) => (f.endsWith(".md") || f.endsWith(".txt")) && f.toLowerCase() !== "readme.md"
    );
    const slugs = new Set(topics.map((t) => t.slug));
    return files.filter((f) => !slugs.has(toSlug(f.replace(/\.(md|txt)$/, ""))));
  } catch {
    return [];
  }
}

function section(title, items, emptyMsg) {
  if (items.length === 0) return `### ${title}\n\n${emptyMsg}\n`;
  return `### ${title} (${items.length})\n\n${items.map((i) => `- ${i}`).join("\n")}\n`;
}

async function main() {
  const topics = await loadTopics();
  const issues = healthCheck(topics);
  const raw = await uncompiledRaw(topics);

  await writeFile(INDEX_FILE, buildIndex(topics), "utf8");

  const date = new Date().toISOString().slice(0, 10);
  const totalIssues =
    issues.broken.length + issues.orphans.length + issues.missing.length + issues.duplicates.length;
  let report = `# Health check — ${date}\n\n`;
  report += `${topics.length} topics · ${totalIssues} issues · ${raw.length} uncompiled raw source(s)\n\n`;
  report += section("Broken backlinks (relatedTopics → unknown slug)", issues.broken, "None ✓") + "\n";
  report += section("Missing frontmatter", issues.missing, "None ✓") + "\n";
  report += section("Orphan topics (no links in or out)", issues.orphans, "None ✓") + "\n";
  report += section("Duplicate slugs", issues.duplicates, "None ✓") + "\n";
  report += section("Raw sources not yet compiled", raw, "None — raw/ is fully compiled ✓") + "\n";

  await mkdir(OUTPUTS_DIR, { recursive: true });
  const reportFile = join(OUTPUTS_DIR, `health-check-${date}.md`);
  await writeFile(reportFile, report, "utf8");

  console.log(`✓ Wrote ${INDEX_FILE.replace(root + "/", "").replace(root + "\\", "")}`);
  console.log(`✓ Wrote outputs/health-check-${date}.md`);
  console.log(
    `\n${topics.length} topics · ${issues.broken.length} broken links · ` +
      `${issues.orphans.length} orphans · ${issues.missing.length} missing-fields · ` +
      `${raw.length} uncompiled`
  );
  if (totalIssues > 0) {
    console.log("\nSee the health report for details.");
  }
}

main().catch((err) => {
  console.error("knowledge: failed —", err.message);
  process.exit(1);
});
